FROM python:3.10

WORKDIR /Users/1zuu/Library/Mobile Documents/com~apple~CloudDocs/ML STU/Docker for Data Science/Churn Prediction

COPY requirements.txt .
RUN pip install -r requirements.txt

CMD ["python","train.py"]